version: '3.8'

services:
  web:
    # OJO: Aquí ya no dice "build", sino "image". Descarga la imagen empaquetada.
    image: tu_usuario/pos-venta-app:latest
    container_name: pos-venta-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file: ./.env
    networks:
      - pos-network
    depends_on:
      db:
        condition: service_healthy

  db:
    # OJO: Descarga la imagen OFICIAL de base de datos
    image: mysql:8.0
    platform: linux/amd64
    container_name: pos-venta-db
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports: 
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - pos-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

networks:
  pos-network:
    driver: bridge

volumes:
  db_data:
